global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5000']
  - job_name: 'app-service'
    static_configs:
      - targets: ['app-service:5001']
  - job_name: 'calculator-service'
    static_configs:
      - targets: ['calculator-service:5002']
  - job_name: 'timer-service'
    static_configs:
      - targets: ['timer-service:5003']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
